###
#> {%
#client.global.set("id2", "1");
#%}

### GET request to example server
GET http://localhost:8080/api/student/get-all
Authorization: Basic user:user
###
###
POST http://localhost:8080/api/student/create
Content-Type: application/json

{
  "firstName": "user",
  "lastName": "user",
  "email": "user@mail.com",
  "city": "user",
  "password": "user",
  "role": "USER"
}
###
DELETE http://localhost:8080/api/student/delete/1
###
GET http://localhost:8080/api/student/2
###
PUT http://localhost:8080/api/student/update/3
Content-Type: application/json

{
  "firstName": "{{$random.alphabetic(6)}}",
  "lastName": "{{$random.alphabetic(8)}}",
  "email": "{{$random.email}}",
  "city": "{{$random.alphabetic(12)}}"
}
###
